using backend.Models.Api;
using backend.Models.Domain;

namespace backend.Services.Mappers
{
    public class BucketMapper
    {
        public static Bucket ToEntity(BucketDto dto) // Convert a DTO to an entity with an ID for updating
        {
            return new Bucket
            {
                Id = dto.Id,
                Title = dto.Title,
                Description = dto.Description
            };
        }

        public static Bucket ToEntity(CreateBucket dto) // dto to a new bucket for creating
        {
            return new Bucket
            {
                // id will be autogenerated
                Title = dto.Title,
                Description = dto.Description
            };
        }
        
        public static BucketDto ToDto(Bucket bucket)
        {
            return new BucketDto
            {
                Id = bucket.Id,
                Title = bucket.Title,
                Description = bucket.Description
            };
        }
    }
}
