using backend.Models.Api;
using backend.Models.Domain;

namespace backend.Services.Mappers
{
    public class BucketMapper
    {
        public static Bucket ToEntity(ApiBucket apiBucket) // Convert a DTO to an entity with an ID for updating
        {
            return new Bucket
            {
                Id = apiBucket.Id,
                Title = apiBucket.Title,
                Description = apiBucket.Description
            };
        }

        public static Bucket ToEntity(ApiBucketCreate createBucket) // dto to a new bucket for creating
        {
            return new Bucket
            {
                // id will be autogenerated
                Title = createBucket.Title,
                Description = createBucket.Description
            };
        }
        
        public static ApiBucket ToDto(Bucket bucket)
        {
            return new ApiBucket
            {
                Id = bucket.Id,
                Title = bucket.Title,
                Description = bucket.Description
            };
        }
    }
}
