using backend.Models.Api;
using backend.Models.Domain;

namespace backend.Services.Mappers
{
    public class ItemMapper
    {
        public static Item ToEntity(ApiItem dto) // Convert a DTO to an entity with an ID for updating
        {
            return new Item
            {
                Id = dto.Id,
                Title = dto.Title!,
                Description = dto.Description,
                Reminder = dto.Reminder,
                DueDate = dto.DueDate,
                Frequency = dto.Frequency,
                IsComplete = dto.IsComplete
            };
        }
        
        public static Item ToEntity(ApiItemCreate dto) // dto to a new item for creating
        {
            return new Item
            {
                // id will be autogenerated
                Title = dto.Title,
                Description = dto.Description,
                Reminder = dto.Reminder,
                DueDate = dto.DueDate,
                Frequency = dto.Frequency,
                IsComplete = false
            };
        }

        public static ApiItem ToDto(Item item)
        {
            return new ApiItem
            {
                Id = item.Id,
                Title = item.Title,
                Description = item.Description,
                Reminder = item.Reminder,
                DueDate = item.DueDate,
                Frequency = item.Frequency,
                IsComplete = item.IsComplete
            };
        }
    }
}
