using backend.Models.Api;
using backend.Models.Domain;

namespace backend.Services.Mappers
{
    public class ItemMapper
    {
        public static Item ToEntity(ApiItem apiItem) // Convert a DTO to an entity with an ID for updating
        {
            return new Item
            {
                Id = apiItem.Id,
                Title = apiItem.Title,
                Description = apiItem.Description,
                Reminder = apiItem.Reminder,
                DueDate = apiItem.DueDate,
                Frequency = apiItem.Frequency,
                IsComplete = apiItem.IsComplete,
                BucketId = apiItem.BucketId
            };
        }
        
        public static Item ToEntity(ApiItemCreate createItem) // dto to a new item for creating
        {
            return new Item
            {
                // id will be autogenerated
                Title = createItem.Title,
                Description = createItem.Description,
                Reminder = createItem.Reminder,
                DueDate = createItem.DueDate,
                Frequency = createItem.Frequency,
                BucketId = createItem.BucketId
            };
        }

        public static ApiItem ToDto(Item item)
        {
            return new ApiItem
            {
                Id = item.Id,
                Title = item.Title,
                Description = item.Description,
                Reminder = item.Reminder,
                DueDate = item.DueDate,
                Frequency = item.Frequency,
                IsComplete = item.IsComplete,
                BucketId = item.BucketId
            };
        }
    }
}
